# Generated by Django 5.1.6 on 2025-02-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario/')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.PositiveIntegerField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.restaurante')),
            ],
        ),
    ]
