# Generated by Django 5.1.6 on 2025-02-07 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
