# Generated by Django 5.1.6 on 2025-02-07 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_asignacion_options_alter_inventario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.restaurante'),
        ),
    ]
