# Generated by Django 5.1.6 on 2025-02-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='restaurante_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='inventario.restaurante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='restaurante_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='inventario.restaurante'),
            preserve_default=False,
        ),
    ]
