# Generated by Django 5.1.6 on 2025-02-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_inventario_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='grupo',
            field=models.CharField(blank=True, choices=[('Loza', 'Losa'), ('Plaqué', 'Platé'), ('Cristalería', 'Cristalería'), ('E. Servicio', 'E. Servicio'), ('Ut. Bar', 'Ut. Bar'), ('Ut. Cocina', 'Ut. Cocina'), ('Portamenús', 'Portamenús'), ('Manteelería', 'Manteelería'), ('Decoraciones', 'Decoraciones')], max_length=255, null=True),
        ),
    ]
